version: '3.1'
services:
  ewm-service-db:
    image: postgres:14-alpine
    container_name: ewm-service-db-container
    ports:
      - "6431:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db-container
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-stats:
    build: ewm-stats
    image: ewm-stats-image
    container_name: ewm-stats-container
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewm-stats

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
      - ewm-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm-service
      - STATS_SERVER_URL=http://ewm-stats:9090