version: '3.1'
services:
  ewm-service-db:
    image: postgres:14-alpine
    container_name: ewm-service-db-container
    ports:
      - "6431:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-server-db:
    image: postgres:14-alpine
    container_name: stats-server-db-container
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-server:
    build: stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-server-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/stats-server

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm-service
      - STATS_SERVER_URL=http://stats-server:9090